dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Fe7WyaZW0hp90Joh/s0eh/sGqLq2Qz5KEDjGSfffDqVDieRU6gHwm5DEgY+6dkV1lu37UkHIO8knd5t+/fG/yJmb5rGr1Pyamj0bAJ5TZg5S9bDKWU1Qe4e9DrQIpPz1F5+G8EjP4l1ANjsiK08dzk+wKd9wB8Rg1a0J21C3HdeOmnvrnfOjJgV87KSPUsDS+wr50QeYDvfiXtDqXt4qovtnS9nkoGLClYDCidsJGTPpXfymwiiEM1LX/QUBPjrbcOWwBYrpcjidIWFV8EJOCFCR3j7r3aVYDXggjJlJPpGTrn4NBND5E6TnPJNhcz178WzxzoysWB1rgX1DLz4tGMKltts2ADMhA+KtMMFSMAwu2u8DssoR8sCnc3ZinC/FVLxP776zGPxcPlPJv7RumK+mEsEdp7qKuw4wbiU+vS6PhIoFGsVd4CDI5BonFEzbfdj0Ye8+NqsfSHfvQ/NNyfqN9RE2Iw96+K7zHl568skyc6pfW6+Q3SytW4y81TOGPs3gVuCZ+QRmUzFdH0XWtkMxhnQhX4pYUymufdJhzsTn4n4tvJy4Ymxh/wH8MkoQGu6rZpWSSie+1UuEnoW9TVQh1N2/kCCqApYrEBD9mVBYCnXopZNOaIdr4RQ2JMrqLDeFR3EdIh9YppAn51/YoTeszBZoZEbBRtkaSqhnmPU=
