dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: EjdWBCBXdfAU3SEHBTM3Rs4ZPFzRP4RxOnHTCJLJUsuWYoEdYeIxWIQUg5HbA6bXdK4wn0b8RsD2Qoroti9UxKszEGowExfhspivV+Ynv3BgmIgDgATHjS7xQuCvFpSZZgIZWHgVZc6Y11AkvbwV2trM3JhiuECEnFRgtlU0fHSvB/0E7dyWS9TxdkGmSk57XrBBbp6r9K0cLhFoE88QXCjJWvcLc/FBqxUIHd3izu0sOIFr4vZDQ4LSALeu9cD8bUpqpefTsvN/azkzR8b2sEY0n9bNJ5mWErAanL1Q3c9i83SwIwFu0btUUMYt//0JDt6d5zEW0vU3KTim6Sm/GKkL7i+/xbgdSugCwbAozezWKVkC3bYNxv2gYnxz+seHVTexELdTaXKFzwJvHJNdqLaSdk2L1wMkuo+lMcT4T682P0i+JJHjYv4MqRquS3T42WXzqpzzRdAXjgDylJe7rdQdAS/9Mhtz+63mOzLKjbRHojHEhTQQK5Sn+BmGap2pX1X0/4WJR1z84Hmez/h1ZFlnpgxZIoOHd3J4jS4WcALufy86vYwFLqPcQ0skKSNUWJ87gLMVgK8kYrxSyq6xmipS2RHX2o40lJQkhjGn2TZl0veEaYznsZ1OTJ8Arx7n4xf8jdVai6OeFpKI/gyGquiLWJVXR4iv82QpncdoSfk=
