global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_tegletsov'
