version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - comment_db
         - post_db
  ui:
    image: ${USERNAME}/ui
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      - back_net
      - front_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      - back_net
      - front_net
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
  front_net:
