version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
         - comment_db
         - post_db
  ui:
    image: ${USERNAME}/ui
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
  front_net:
