kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: Dt5f7luAKUN+ltDRLOdfSHNwyhJBVOZmLCGw/lpPiGU=
      - identity: {}
